<?php
// includes/config.php

define('SITE_NAME', 'DB Digital Agency');
define('BASE_URL', '');
define('ASSETS_URL', BASE_URL . 'assets/');

// Navigation principale
$nav_items = [
    ['url' => 'index.php', 'label_key' => 'nav_home', 'class' => ''],
    ['url' => 'about.php', 'label_key' => 'nav_about', 'class' => ''],
    ['url' => 'services.php', 'label_key' => 'nav_services', 'class' => ''],
    ['url' => 'projects.php', 'label_key' => 'nav_projects', 'class' => ''],
    ['url' => 'blog.php', 'label_key' => 'nav_blog', 'class' => ''],
    // ['url' => 'contact.php', 'label_key' => 'nav_contact', 'class' => ''],
];

// Coordonnées
define('CONTACT_ADDRESS', 'Entrée Carriere, Nkoabang, Yaoundé, Cameroon');
define('CONTACT_PHONE_1', '+237 691 323 249');
define('CONTACT_PHONE_2', '+237 658 910 343');
define('CONTACT_PHONE_3', '+237 640 819 846');
define('CONTACT_EMAIL', 'contact@dbdigitalagency.com');

// WhatsApp (numéro sans espaces pour l'URL)
define('WHATSAPP_NUMBER', '237691323249');

// Réseaux sociaux
$social_links = [
    'facebook'  => '#',
    'twitter'   => '#',
    'instagram' => '#',
    'linkedin'  => '#',
];

// ============================================
// SYSTÈME MULTILINGUE
// ============================================
session_start();

// Langues disponibles
$available_langs = ['en', 'fr'];
$default_lang = 'fr';

// Détection de la langue
if (isset($_GET['lang']) && in_array($_GET['lang'], $available_langs)) {
    $_SESSION['lang'] = $_GET['lang'];
    $current_lang = $_GET['lang'];
} elseif (isset($_SESSION['lang']) && in_array($_SESSION['lang'], $available_langs)) {
    $current_lang = $_SESSION['lang'];
} else {
    $current_lang = $default_lang;
}

// ============================================
// CONFIGURATION BASE DE DONNÉES
// ============================================
define('DB_HOST', 'localhost');
define('DB_NAME', 'dbdigitalagency');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_CHARSET', 'utf8mb4');

// ============================================
// CONFIGURATION EMAIL / SMTP
// ============================================
define('SMTP_HOST', 'smtp.gmail.com');      // ou smtp.mailgun.com, smtp.sendgrid.net
define('SMTP_PORT', 587);                   // 587 pour TLS, 465 pour SSL
define('SMTP_USERNAME', 'votre-email@gmail.com');  // MODIFIEZ ICI
define('SMTP_PASSWORD', 'votre-mot-de-passe-app'); // MODIFIEZ ICI (mot de passe d'application)
define('SMTP_ENCRYPTION', 'tls');            // tls ou ssl
define('SMTP_FROM_EMAIL', 'noreply@dbdigitalagency.com');
define('SMTP_FROM_NAME', 'DB Digital Agency');
define('ADMIN_EMAIL', 'contact@dbdigitalagency.com');

// ============================================
// TRADUCTIONS ET CONTENU
// ============================================

$translations = [
    'en' => [
        'nav_home' => 'Home',
        'nav_about' => 'About Us',
        'nav_services' => 'Services',
        'nav_projects' => 'Projects',
        'nav_blog' => 'Blog',
        'nav_contact' => 'Contact',
        'btn_quote' => 'Get A Quote',
        'btn_read_more' => 'Read More',
        'btn_see_all' => 'See All',
        'btn_contact' => 'Contact Us',
        'meta_suffix' => 'Digital Agency',
        'meta_default_description' => 'DB Digital Agency - Strategy, design, web development and growth marketing for ambitious businesses in Cameroon.',
        'hero_title' => 'Build, acquire, grow',
        'hero_desc' => 'We design high-converting brands, websites and acquisition systems that help ambitious businesses grow in Cameroon and across Africa.',
        'features_growing' => 'Digital Strategy',
        'features_finance' => 'Growth Marketing',
        'features_tax' => 'Brand & Design',
        'about_subtitle' => 'Who we are',
        'about_page_subtitle' => 'Who we are',
        'about_title' => 'Innovation and growth for digital businesses',
        'about_page_title' => 'Innovation and growth for digital businesses',
        'about_page_desc' => 'We are a Yaoundé-based digital agency helping businesses create strong online brands, convert more customers and scale through high-performance digital experiences.',
        'about_ceo' => 'CEO, DB Digital Agency',
        'services_subtitle' => 'What We Do For You',
        'services_title' => 'A Wide Range Of Services For Your Business!',
        'services_btn' => 'See All Services',
        'services_page_title' => 'Our Services',
        'services_page_lead' => 'From strategy to execution: design, development and growth marketing to build a strong digital presence and measurable results.',
        'services_block_subtitle' => 'What we do',
        'services_block_title' => 'A complete digital team for your growth',
        'services_block_cta' => 'Request a Quote',
        'services_details_cta' => 'Request a quote',
        'counter_projects' => 'Projects Delivered',
        'counter_clients' => 'Satisfied Clients',
        'counter_awards' => 'Awards Earned',
        'counter_countries' => 'Countries Served',
        'call_for_more_info' => 'Call For More Info',
        'call_desc' => 'Let\'s Request a Schedule For Free Consultation',
        'projects_subtitle' => 'Case Studies',
        'projects_title' => 'We have helped brands grow with strong digital solutions',
        'projects_btn' => 'See All Projects',
        'team_subtitle' => 'Expert People',
        'team_title' => 'Our Dedicated Team Members',
        'team_lead' => 'A lean senior team combining strategy, design, engineering and performance marketing to deliver tangible business outcomes.',
        'team_role_strategy' => 'Digital Strategist',
        'team_role_design' => 'UI/UX Designer',
        'team_role_dev' => 'Full‑stack Developer',
        'team_role_marketing' => 'Growth Marketer',
        'testimonial_title' => 'What Our Clients Say',
        'blog_subtitle' => 'Insights & Articles',
        'blog_title' => 'Read Our Latest Updates',
        'blog_page_title' => 'Insights',
        'blog_page_description' => 'Actionable articles on strategy, design, web, SEO and acquisition for businesses in Cameroon.',
        'blog_no_posts' => 'No posts found matching your criteria.',
        'blog_sidebar_categories' => 'Categories',
        'blog_sidebar_recent' => 'Recent Posts',
        'blog_sidebar_tags' => 'Tags',
        'contact_sales_title' => 'Sales',
        'contact_sales_desc' => 'For new projects and partnerships',
        'contact_general_title' => 'General',
        'contact_general_desc' => 'Questions, information and orientation',
        'contact_support_title' => 'Support',
        'contact_support_desc' => 'Technical support and assistance',
        'footer_newsletter' => 'Subscribe to Our Newsletter',
        'footer_newsletter_desc' => 'Sign up to our weekly newsletter to get the latest updates.',
        'footer_email_placeholder' => 'enter your e-mail',
        'footer_subscribe' => 'Subscribe',
        'footer_no_spam' => 'We don\'t send you any spam',
        'footer_copyright' => 'Copyright © dbdigitalagency | All Right Reserved',
        'footer_info_title' => 'Information',
        'footer_menu_title' => 'Menu',
        'footer_opening_hours' => 'Mon – Sat: 8 am – 6 pm',
        'footer_sunday' => 'Sunday',
        'footer_closed' => 'CLOSED',
        'footer_menu_company' => 'Company',
        'footer_menu_careers' => 'Careers',
        'footer_menu_press' => 'Press',
        'footer_menu_privacy' => 'Privacy Policy',
        'footer_quicklinks_title' => 'Quick Links',
        'footer_ql_how' => 'How it works',
        'footer_ql_partners' => 'Partners',
        'footer_ql_testimonials' => 'Testimonials',
        'footer_ql_cases' => 'Case studies',
        'footer_ql_pricing' => 'Pricing',
        'whatsapp_text' => 'Chat on WhatsApp',
        'quote_title' => 'Request a Quote',
        'quote_subtitle' => 'Get your custom digital quote today',
        'quote_desc' => 'Tell us about your project and we will provide a tailored proposal that fits your goals.',
        'quote_quick_response' => 'Fast response time',
        'quote_secure_approach' => 'Secure and professional process',
        'quote_talk_to_us' => 'Talk to Us',
        'quote_step_service' => 'Service',
        'quote_step_project' => 'Project',
        'quote_step_contact' => 'Contact',
        'quote_step_review' => 'Review',
        'quote_service_label' => 'Service',
        'quote_subject_label' => 'Project Subject',
        'quote_type_label' => 'Project Type',
        'quote_budget_label' => 'Budget',
        'quote_start_label' => 'Start Date',
        'quote_message_label' => 'Project Details',
        'quote_brief_label' => 'Upload Brief',
        'quote_file_hint' => 'Attach any relevant project documents here.',
        'quote_fullname_label' => 'Full Name',
        'quote_company_label' => 'Company',
        'quote_email_label' => 'Email Address',
        'quote_whatsapp_label' => 'WhatsApp Number',
        'quote_review_title' => 'Review',
        'quote_ask_question' => 'Send Request',
        'quote_innovation_title' => 'Innovation Starts Here',
        'quote_innovation_desc' => 'Tell us what you want to build. We will reply with a clear plan, timeline and budget range — then we can refine together.',
        'quote_option_email' => 'Send by Email',
        'quote_option_whatsapp' => 'Send via WhatsApp',
        'quote_send_method' => 'Send Method',
        'quote_step_of' => 'Step',
        'quote_step_of_total' => 'of',
        'quote_continue' => 'Continue',
        'quote_back' => 'Back',
        'quote_project_details_title' => 'Project details',
        'quote_project_details_desc' => 'Help us understand the scope and timeline of your project.',
        'quote_contact_details_title' => 'Your details',
        'quote_contact_details_desc' => 'How can we reach you? We will use this to respond to your request.',
        'quote_review_send_title' => 'Review & send',
        'quote_review_send_desc' => 'Review your request before sending.',
        'quote_select_service_desc' => 'Select one or more services that match your needs.',
        'quote_placeholder_subject' => 'e.g. E‑commerce website',
        'quote_placeholder_message' => 'Tell us more about your needs...',
        'quote_placeholder_fullname' => 'Full name',
        'quote_placeholder_company' => 'Company name',
        'quote_placeholder_email' => 'your@email.com',
        'quote_placeholder_whatsapp' => '+237 6XX XXX XXX',
        'quote_file_none' => 'No file chosen',
        'quote_validation_select_service' => 'Please select at least one service.',
        'quote_validation_required' => 'Required',
        'quote_validation_email' => 'Valid email required',
        'quote_send_request' => 'Send request',
        'quote_send_both_title' => 'Email + WhatsApp',
        'quote_send_both_desc' => 'Your request is emailed to our team and you will be redirected to WhatsApp to finalize.',
        'quote_svc_strategy_title' => 'Digital Strategy',
        'quote_svc_strategy_sub' => 'Strategy & consulting',
        'quote_svc_web_title' => 'Web Development',
        'quote_svc_web_sub' => 'Websites & apps',
        'quote_svc_brand_title' => 'Branding & Design',
        'quote_svc_brand_sub' => 'UI/UX & identity',
        'quote_svc_marketing_title' => 'Growth Marketing',
        'quote_svc_marketing_sub' => 'SEO & acquisition',
        'quote_type_new' => 'New project',
        'quote_type_redesign' => 'Redesign',
        'quote_type_maintenance' => 'Maintenance',
        'quote_type_consulting' => 'Consulting only',
        'quote_start_immediately' => 'Immediately',
        'quote_start_1_week' => 'Within 1 week',
        'quote_start_1_month' => 'Within 1 month',
        'quote_start_flexible' => 'Flexible',
        'quote_optional' => 'optional',
        'quote_success_email' => 'Your quote request has been sent successfully! We will contact you soon.',
        'quote_success_whatsapp' => 'Redirecting to WhatsApp...',
        'quote_error_db' => 'Unable to save your request. Please try again.',
        'quote_error_email' => 'Request saved but email failed. We will contact you via WhatsApp.',
        'quote_whatsapp_intro' => 'Hello DB Digital Agency, I would like a quote for the following project:',
        'quote_whatsapp_service' => 'Service',
        'quote_whatsapp_subject' => 'Subject',
        'quote_whatsapp_type' => 'Type',
        'quote_whatsapp_budget' => 'Budget',
        'quote_whatsapp_start' => 'Start',
        'quote_whatsapp_name' => 'Name',
        'quote_whatsapp_company' => 'Company',
        'quote_whatsapp_email' => 'Email',
        'quote_whatsapp_message' => 'Message',
        'quote_db_saved' => 'Request saved in database',
        'breadcrumb_home' => 'Home',
        'breadcrumb_about' => 'About',
        'breadcrumb_services' => 'Services',
        'breadcrumb_projects' => 'Projects',
        'breadcrumb_blog' => 'Blog',
        'breadcrumb_contact' => 'Contact',
        'about_subtitle' => 'Who we are',
        'about_title' => 'Innovation and growth for digital businesses',
        'about_desc' => 'We are a Yaoundé-based digital agency helping businesses create strong online brands, convert more customers and scale through high-performance digital experiences.',
        'homepage_exp_years' => 'Years',
        'homepage_exp_label' => 'of experience building digital solutions',
        'homepage_about_lead' => 'We deliver end-to-end digital services — strategy, design, development and acquisition — to help brands grow with measurable results.',
        'homepage_about_list_1' => 'Strategy-first approach, execution-ready',
        'homepage_about_list_2' => 'Conversion-focused UX and copy',
        'homepage_about_list_3' => 'SEO + performance by default',
        'homepage_about_list_4' => 'Campaigns optimized for ROI',
        'homepage_about_conclusion' => 'Our team pairs creative and technical excellence to turn your objectives into a scalable digital system.',
        'about_expertise' => 'Digital Consulting & Growth Agency',
        'about_expertise_title' => 'Digital product, growth and branding expertise',
        'about_expertise_subtitle' => 'Expertise areas',
        'about_expertise_desc' => 'We help brands design high-converting digital journeys and launch acquisition campaigns that deliver measurable growth.',
        'about_skill_strategy' => 'Digital Strategy',
        'about_skill_brand' => 'Brand Experience',
        'about_skill_growth' => 'Customer Acquisition',
        'about_service_btn' => 'Start a Project',
        'about_company_type_1' => 'Digital Creative Agency',
        'about_company_type_2' => 'Professional Problem Solutions',
        'about_company_type_3' => 'Web Design & Development',
        'services_page_subtitle' => 'Comprehensive solutions for your growth',
        'search_placeholder' => 'Search Here...',
        'search_title' => 'Search here',
    ],
    'fr' => [
        'meta_suffix' => 'Agence Digitale',
        'meta_default_description' => 'DB Digital Agency - Stratégie, design, développement web et marketing d’acquisition pour les entreprises ambitieuses au Cameroun.',
        'nav_home' => 'Accueil',
        'nav_about' => 'À Propos',
        'nav_services' => 'Services',
        'nav_projects' => 'Projets',
        'nav_blog' => 'Blog',
        'nav_contact' => 'Contact',
        'btn_quote' => 'Demander un Devis',
        'btn_read_more' => 'En Savoir Plus',
        'btn_see_all' => 'Voir Tout',
        'btn_contact' => 'Nous Contacter',
        'hero_title' => 'CONSTRUIRE. ACQUÉRIR. CROÎTRE.',
        'hero_desc' => 'Nous concevons des marques, sites web et systèmes d’acquisition qui transforment votre présence digitale en croissance mesurable.',
        'features_growing' => 'Stratégie Digitale',
        'features_finance' => 'Marketing d\'Acquisition',
        'features_tax' => 'Branding & Design',
        'about_subtitle' => 'Qui nous sommes',
        'about_page_subtitle' => 'Qui nous sommes',
        'about_title' => 'Innovation et croissance pour les entreprises digitales',
        'about_page_title' => 'Innovation et croissance pour les entreprises digitales',
        'about_page_desc' => 'Nous sommes une agence digitale basée à Yaoundé, aidant les entreprises à créer des marques fortes, à convertir davantage de clients et à croître grâce à des expériences digitales performantes.',
        'about_ceo' => 'PDG, DB Digital Agency',
        'services_subtitle' => 'Ce Que Nous Faisons Pour Vous',
        'services_title' => 'Une Large Gamme de Services Pour Votre Entreprise !',
        'services_btn' => 'Voir Tous les Services',
        'services_page_title' => 'Nos Services',
        'services_page_lead' => 'De la stratégie à l’exécution : design, développement et marketing d’acquisition pour une présence digitale forte et des résultats mesurables.',
        'services_block_subtitle' => 'Ce que nous faisons',
        'services_block_title' => 'Une équipe digitale complète pour votre croissance',
        'services_block_cta' => 'Demander un devis',
        'services_details_cta' => 'Demander un devis',
        'counter_projects' => 'Projets Réalisés',
        'counter_clients' => 'Clients Satisfaits',
        'counter_awards' => 'Récompenses Obtenues',
        'counter_countries' => 'Pays Desservis',
        'call_for_more_info' => 'Appeler pour plus d\'infos',
        'call_desc' =>  'Demandez un rendez-vous pour une consultation gratuite',
        'projects_subtitle' => 'Études de Cas',
        'projects_title' => 'Nous avons aidé des marques à croître grâce à des solutions digitales solides',
        'projects_btn' => 'Voir Tous les Projets',
        'team_subtitle' => 'Experts',
        'team_title' => 'Les Membres de Notre Équipe Dévouée',
        'team_lead' => 'Une équipe senior qui combine stratégie, design, ingénierie et performance marketing pour livrer des résultats business.',
        'team_role_strategy' => 'Stratège Digital',
        'team_role_design' => 'Designer UI/UX',
        'team_role_dev' => 'Développeur Full‑stack',
        'team_role_marketing' => 'Growth Marketer',
        'testimonial_title' => 'Ce Que Disent Nos Clients',
        'blog_subtitle' => 'Actualités & Blogs',
        'blog_title' => 'Lisez Nos Dernières Mises à Jour',
        'blog_page_title' => 'Analyses & Conseils',
        'blog_page_description' => 'Articles actionnables sur la stratégie, le design, le web, le SEO et l’acquisition pour les entreprises au Cameroun.',
        'blog_no_posts' => 'Aucun article ne correspond à vos critères.',
        'blog_sidebar_categories' => 'Catégories',
        'blog_sidebar_recent' => 'Articles récents',
        'blog_sidebar_tags' => 'Tags',
        'contact_sales_title' => 'Commercial',
        'contact_sales_desc' => 'Nouveaux projets et partenariats',
        'contact_general_title' => 'Général',
        'contact_general_desc' => 'Questions, informations et orientation',
        'contact_support_title' => 'Support',
        'contact_support_desc' => 'Assistance technique et support',
        'footer_newsletter' => 'Abonnez-vous à Notre Newsletter',
        'footer_newsletter_desc' => 'Inscrivez-vous à notre newsletter hebdomadaire pour recevoir les dernières actualités.',
        'footer_email_placeholder' => 'entrez votre e-mail',
        'footer_subscribe' => 'S\'abonner',
        'footer_no_spam' => 'Nous ne vous envoyons pas de spam',
        'footer_copyright' => 'Copyright © dbdigitalagency | Tous Droits Réservés',
        'footer_info_title' => 'Informations',
        'footer_menu_title' => 'Menu',
        'footer_opening_hours' => 'Lun – Sam : 8h – 18h',
        'footer_sunday' => 'Dimanche',
        'footer_closed' => 'FERMÉ',
        'footer_menu_company' => 'Entreprise',
        'footer_menu_careers' => 'Carrières',
        'footer_menu_press' => 'Presse',
        'footer_menu_privacy' => 'Politique de confidentialité',
        'footer_quicklinks_title' => 'Liens rapides',
        'footer_ql_how' => 'Comment ça marche',
        'footer_ql_partners' => 'Partenaires',
        'footer_ql_testimonials' => 'Témoignages',
        'footer_ql_cases' => 'Études de cas',
        'footer_ql_pricing' => 'Tarification',
        'whatsapp_text' => 'Discuter sur WhatsApp',
        'quote_title' => 'Demandez un Devis',
        'quote_subtitle' => 'Obtenez votre devis digital personnalisé aujourd\'hui',
        'quote_desc' => 'Parlez-nous de votre projet et nous vous proposerons une proposition adaptée à vos objectifs.',
        'quote_quick_response' => 'Réponse rapide',
        'quote_secure_approach' => 'Processus sécurisé et professionnel',
        'quote_talk_to_us' => 'Parlez-nous',
        'quote_step_service' => 'Service',
        'quote_step_project' => 'Projet',
        'quote_step_contact' => 'Contact',
        'quote_step_review' => 'Revoir',
        'quote_service_label' => 'Service',
        'quote_subject_label' => 'Sujet du Projet',
        'quote_type_label' => 'Type de Projet',
        'quote_budget_label' => 'Budget',
        'quote_start_label' => 'Date de début',
        'quote_message_label' => 'Détails du Projet',
        'quote_brief_label' => 'Télécharger le Brief',
        'quote_file_hint' => 'Joignez ici tous les documents de projet pertinents.',
        'quote_fullname_label' => 'Nom Complet',
        'quote_company_label' => 'Entreprise',
        'quote_email_label' => 'Adresse Email',
        'quote_whatsapp_label' => 'Numéro WhatsApp',
        'quote_review_title' => 'Revoir',
        'quote_ask_question' => 'Envoyer la demande',
        'quote_innovation_title' => 'L\'innovation commence ici',
        'quote_innovation_desc' => 'Parlez-nous de ce que vous voulez construire. Nous vous répondons avec un plan clair, une timeline et une fourchette de budget — puis on affine ensemble.',
        'quote_step_of' => 'Étape',
        'quote_step_of_total' => 'sur',
        'quote_continue' => 'Continuer',
        'quote_back' => 'Retour',
        'quote_project_details_title' => 'Détails du projet',
        'quote_project_details_desc' => 'Aidez-nous à comprendre le périmètre et la timeline de votre projet.',
        'quote_contact_details_title' => 'Vos informations',
        'quote_contact_details_desc' => 'Comment vous joindre ? Nous utiliserons ces infos pour vous répondre.',
        'quote_review_send_title' => 'Vérifier & envoyer',
        'quote_review_send_desc' => 'Vérifiez votre demande avant l’envoi.',
        'quote_select_service_desc' => 'Sélectionnez un ou plusieurs services qui correspondent à votre besoin.',
        'quote_placeholder_subject' => 'ex. Site e‑commerce',
        'quote_placeholder_message' => 'Dites-nous en plus sur votre besoin...',
        'quote_placeholder_fullname' => 'Nom complet',
        'quote_placeholder_company' => 'Nom de l’entreprise',
        'quote_placeholder_email' => 'vous@email.com',
        'quote_placeholder_whatsapp' => '+237 6XX XXX XXX',
        'quote_file_none' => 'Aucun fichier sélectionné',
        'quote_validation_select_service' => 'Veuillez sélectionner au moins un service.',
        'quote_validation_required' => 'Requis',
        'quote_validation_email' => 'Email valide requis',
        'quote_send_request' => 'Envoyer la demande',
        'quote_send_both_title' => 'Email + WhatsApp',
        'quote_send_both_desc' => 'Votre demande est envoyée par email à notre équipe et vous êtes redirigé vers WhatsApp pour finaliser.',
        'quote_svc_strategy_title' => 'Stratégie Digitale',
        'quote_svc_strategy_sub' => 'Stratégie & conseil',
        'quote_svc_web_title' => 'Développement Web',
        'quote_svc_web_sub' => 'Sites & apps',
        'quote_svc_brand_title' => 'Branding & Design',
        'quote_svc_brand_sub' => 'UI/UX & identité',
        'quote_svc_marketing_title' => 'Marketing d’Acquisition',
        'quote_svc_marketing_sub' => 'SEO & acquisition',
        'quote_type_new' => 'Nouveau projet',
        'quote_type_redesign' => 'Refonte',
        'quote_type_maintenance' => 'Maintenance',
        'quote_type_consulting' => 'Conseil uniquement',
        'quote_start_immediately' => 'Immédiatement',
        'quote_start_1_week' => 'Sous 1 semaine',
        'quote_start_1_month' => 'Sous 1 mois',
        'quote_start_flexible' => 'Flexible',
        'quote_optional' => 'optionnel',
        'quote_option_email' => 'Envoyer par Email',
        'quote_option_whatsapp' => 'Envoyer via WhatsApp',
        'quote_send_method' => 'Méthode d\'envoi',
        'quote_success_email' => 'Votre demande de devis a été envoyée avec succès ! Nous vous contacterons bientôt.',
        'quote_success_whatsapp' => 'Redirection vers WhatsApp...',
        'quote_error_db' => 'Impossible de sauvegarder votre demande. Veuillez réessayer.',
        'quote_error_email' => 'Demande sauvegardée mais l\'email a échoué. Nous vous contacterons via WhatsApp.',
        'quote_whatsapp_intro' => 'Bonjour DB Digital Agency, je souhaiterais un devis pour le projet suivant :',
        'quote_whatsapp_service' => 'Service',
        'quote_whatsapp_subject' => 'Sujet',
        'quote_whatsapp_type' => 'Type',
        'quote_whatsapp_budget' => 'Budget',
        'quote_whatsapp_start' => 'Début',
        'quote_whatsapp_name' => 'Nom',
        'quote_whatsapp_company' => 'Entreprise',
        'quote_whatsapp_email' => 'Email',
        'quote_whatsapp_message' => 'Message',
        'quote_db_saved' => 'Demande sauvegardée en base de données',
        'breadcrumb_home' => 'Accueil',
        'breadcrumb_about' => 'À Propos',
        'breadcrumb_services' => 'Services',
        'breadcrumb_projects' => 'Projets',
        'breadcrumb_blog' => 'Blog',
        'breadcrumb_contact' => 'Contact',
        'about_subtitle' => 'Qui sommes-nous',
        'about_title' => 'Construire l\'avenir numérique des entreprises',
        'about_desc' => 'Nous sommes une agence numérique de premier plan basée à Yaoundé, au Cameroun, aidant les entreprises à transformer leur présence numérique et à réaliser une croissance durable grâce à des stratégies innovantes.',
        'homepage_exp_years' => 'Ans',
        'homepage_exp_label' => 'd’expérience sur des projets digitaux',
        'homepage_about_lead' => 'Nous livrons des services digitaux de bout en bout — stratégie, design, développement et acquisition — pour faire croître votre marque avec des résultats mesurables.',
        'homepage_about_list_1' => 'Approche stratégie → exécution',
        'homepage_about_list_2' => 'UX et copy orientés conversion',
        'homepage_about_list_3' => 'SEO + performance par défaut',
        'homepage_about_list_4' => 'Campagnes optimisées pour le ROI',
        'homepage_about_conclusion' => 'Notre équipe combine créativité et excellence technique pour transformer vos objectifs en système digital scalable.',
        'about_expertise' => 'Agence de Conseil Numérique et Croissance',
        'about_expertise_title' => 'Expertise en produit digital, croissance et branding',
        'about_expertise_subtitle' => 'Domaines d\'expertise',
        'about_expertise_desc' => 'Nous aidons les marques à concevoir des parcours digitaux performants et à lancer des campagnes d\'acquisition qui génèrent une croissance mesurable.',
        'about_skill_strategy' => 'Stratégie Numérique',
        'about_skill_brand' => 'Expérience de Marque',
        'about_skill_growth' => 'Croissance Commerciale',
        'about_service_btn' => 'Utiliser nos Services',
        'about_company_type_1' => 'Agence Créative Numérique',
        'about_company_type_2' => 'Solutions Professionnelles',
        'about_company_type_3' => 'Design & Développement Web',
        'services_page_title' => 'Nos Services',
        'services_page_subtitle' => 'Solutions complètes pour votre croissance',
        'search_placeholder' => 'Rechercher ici...',
        'search_title' => 'Recherchez ici',
    ],
];

// Fonction de traduction
function __($key) {
    global $translations, $current_lang;
    return $translations[$current_lang][$key] ?? $key;
}

// Message WhatsApp selon la langue
$whatsapp_messages = [
    'en' => 'Hello DB Digital Agency, I would like a tailored quote for my digital project.',
    'fr' => 'Bonjour DB Digital Agency, je souhaite un devis personnalisé pour mon projet digital.',
];
define('WHATSAPP_MESSAGE', $whatsapp_messages[$current_lang]);

// ============================================
// DONNÉES BLOG
// ============================================
$blog_posts = [
    [
        'id' => 1,
        'title_en' => 'How to Launch a Strong Digital Brand in Cameroon',
        'title_fr' => 'Comment Lancer une Marque Digitale Forte au Cameroun',
        'excerpt_en' => 'Step-by-step guidance to build an impactful digital brand for local audiences.',
        'excerpt_fr' => 'Guide étape par étape pour construire une marque digitale forte adaptée au marché camerounais.',
        'image' => 'h3_blog_img01.jpg',
        'avatar' => 'blog_avatar01.png',
        'author' => 'DB Digital Team',
        'date' => '22 Jan, 2023',
        'category_en' => 'Branding',
        'category_fr' => 'Branding',
        'url' => '#?id=1'
    ],
    [
        'id' => 2,
        'title_en' => 'Digital Transformation for African SMEs',
        'title_fr' => 'Transformation Digitale pour les PME Africaines',
        'excerpt_en' => 'How small and medium businesses in Cameroon can thrive with the right digital tools.',
        'excerpt_fr' => 'Comment les petites et moyennes entreprises camerounaises peuvent prospérer avec les bons outils digitaux.',
        'image' => 'h3_blog_img02.jpg',
        'avatar' => 'blog_avatar02.png',
        'author' => 'DB Digital Team',
        'date' => '25 Jan, 2023',
        'category_en' => 'Strategy',
        'category_fr' => 'Stratégie',
        'url' => '#?id=2'
    ],
    [
        'id' => 3,
        'title_en' => 'Growth Marketing for Startups in Cameroon',
        'title_fr' => 'Marketing de Croissance pour les Startups au Cameroun',
        'excerpt_en' => 'Performance marketing tactics to turn traffic into paying customers.',
        'excerpt_fr' => 'Tactiques de marketing de performance pour transformer le trafic en clients payants.',
        'image' => 'h3_blog_img03.jpg',
        'avatar' => 'blog_avatar03.png',
        'author' => 'DB Digital Team',
        'date' => '28 Jan, 2023',
        'category_en' => 'Marketing',
        'category_fr' => 'Marketing',
        'url' => '#?id=3'
    ],
    [
        'id' => 4,
        'title_en' => 'Website Conversion Best Practices',
        'title_fr' => 'Meilleures Pratiques de Conversion Web',
        'excerpt_en' => 'UX, copy and design techniques to increase leads and customer trust.',
        'excerpt_fr' => 'Techniques UX, rédaction et design pour augmenter les prospects et la confiance client.',
        'image' => 'h3_blog_img04.jpg',
        'avatar' => 'blog_avatar04.png',
        'author' => 'DB Digital Team',
        'date' => '01 Feb, 2023',
        'category_en' => 'Web',
        'category_fr' => 'Web',
        'url' => '#?id=4'
    ],
    [
        'id' => 5,
        'title_en' => 'Social Media Strategies for Local Business Growth',
        'title_fr' => 'Stratégies Social Media pour la Croissance des Entreprises Locales',
        'excerpt_en' => 'Practical tips to use social platforms as a sales and brand engine.',
        'excerpt_fr' => 'Conseils pratiques pour utiliser les réseaux sociaux comme levier de vente et de notoriété.',
        'image' => 'h3_blog_img05.jpg',
        'avatar' => 'blog_avatar05.png',
        'author' => 'DB Digital Team',
        'date' => '05 Feb, 2023',
        'category_en' => 'Social',
        'category_fr' => 'Social',
        'url' => '#?id=5'
    ],
    [
        'id' => 6,
        'title_en' => 'Data-Driven Decisions for Growing Companies',
        'title_fr' => 'Décisions Basées sur les Données pour les Entreprises en Croissance',
        'excerpt_en' => 'How business analytics help prioritize digital investments and optimize campaigns.',
        'excerpt_fr' => 'Comment l’analytique d’entreprise aide à prioriser les investissements digitaux et optimiser les campagnes.',
        'image' => 'h3_blog_img06.jpg',
        'avatar' => 'blog_avatar06.png',
        'author' => 'DB Digital Team',
        'date' => '10 Feb, 2023',
        'category_en' => 'Analytics',
        'category_fr' => 'Analytique',
        'url' => '#?id=6'
    ],
];

$blog_categories = [
    ['name_en' => 'Strategy', 'name_fr' => 'Stratégie', 'count' => 6],
    ['name_en' => 'Branding', 'name_fr' => 'Branding', 'count' => 4],
    ['name_en' => 'Web', 'name_fr' => 'Web', 'count' => 6],
    ['name_en' => 'SEO', 'name_fr' => 'SEO', 'count' => 5],
    ['name_en' => 'Paid Media', 'name_fr' => 'Publicité', 'count' => 5],
    ['name_en' => 'Analytics', 'name_fr' => 'Analytique', 'count' => 3],
];

$blog_tags = [
    ['en' => 'SEO', 'fr' => 'SEO'],
    ['en' => 'Conversion', 'fr' => 'Conversion'],
    ['en' => 'UI/UX', 'fr' => 'UI/UX'],
    ['en' => 'Ads', 'fr' => 'Ads'],
    ['en' => 'Content', 'fr' => 'Contenu'],
];

// ============================================
// DONNÉES PROJETS
// ============================================
$projects = [
    [
        'id' => 1,
        'title_en' => 'Digital Banking Platform',
        'title_fr' => 'Plateforme Bancaire Digitale',
        'category_en' => 'Fintech',
        'category_fr' => 'Fintech',
        'image' => 'h4_services_img01.jpg',
        'icon' => 'flaticon-healthcare',
        'description_en' => 'Complete website and onboarding experience for a local bank.',
        'description_fr' => 'Refonte du site et de l\'expérience d\'intégration pour une banque locale.',
    ],
    [
        'id' => 2,
        'title_en' => 'E-Commerce Marketplace',
        'title_fr' => 'Marketplace E-Commerce',
        'category_en' => 'Marketplace',
        'category_fr' => 'Marketplace',
        'image' => 'h4_services_img02.jpg',
        'icon' => 'flaticon-protection',
        'description_en' => 'A shopping platform connecting local artisans with online buyers.',
        'description_fr' => 'Une plateforme commerciale reliant les artisans locaux aux acheteurs en ligne.',
    ],
    [
        'id' => 3,
        'title_en' => 'Logistics Management Tool',
        'title_fr' => 'Outil de Gestion Logistique',
        'category_en' => 'Logistics',
        'category_fr' => 'Logistique',
        'image' => 'h4_services_img03.jpg',
        'icon' => 'flaticon-ship',
        'description_en' => 'Digital workflow for tracking orders and deliveries in agribusiness.',
        'description_fr' => 'Workflow digital pour le suivi des commandes et livraisons en agrobusiness.',
    ],
    [
        'id' => 4,
        'title_en' => 'Real Estate Portal',
        'title_fr' => 'Portail Immobilier',
        'category_en' => 'PropTech',
        'category_fr' => 'PropTech',
        'image' => 'h4_services_img04.jpg',
        'icon' => 'flaticon-house',
        'description_en' => 'A listing platform for property agencies and property seekers.',
        'description_fr' => 'Plateforme d\'annonces pour agences immobilières et acheteurs potentiels.',
    ],
    [
        'id' => 5,
        'title_en' => 'Tourism Booking Engine',
        'title_fr' => 'Moteur de Réservation Touristique',
        'category_en' => 'Travel',
        'category_fr' => 'Voyage',
        'image' => 'h4_services_img05.jpg',
        'icon' => 'flaticon-travel-insurance',
        'description_en' => 'Online reservation system tailored to Cameroon tourism operators.',
        'description_fr' => 'Système de réservation en ligne conçu pour les acteurs du tourisme camerounais.',
    ],
    [
        'id' => 6,
        'title_en' => 'Corporate Dashboard',
        'title_fr' => 'Tableau de Bord Corporate',
        'category_en' => 'Analytics',
        'category_fr' => 'Analytique',
        'image' => 'h4_services_img06.jpg',
        'icon' => 'flaticon-briefcase-1',
        'description_en' => 'A business intelligence dashboard for leaders to track growth metrics.',
        'description_fr' => 'Tableau de bord d\'intelligence pour suivre les indicateurs de croissance.',
    ],
    [
        'id' => 7,
        'title_en' => 'Brand Identity Refresh',
        'title_fr' => 'Refonte d\'Identité de Marque',
        'category_en' => 'Branding',
        'category_fr' => 'Branding',
        'image' => 'h4_services_img07.jpg',
        'icon' => 'flaticon-family-insurance',
        'description_en' => 'A full branding and digital presence update for a service business.',
        'description_fr' => 'Refonte complète de l\'identité et de la présence digitale d\'une entreprise de services.',
    ],
    [
        'id' => 8,
        'title_en' => 'Sales Funnel Optimization',
        'title_fr' => 'Optimisation de Tunnel de Vente',
        'category_en' => 'Marketing',
        'category_fr' => 'Marketing',
        'image' => 'h4_services_img08.jpg',
        'icon' => 'flaticon-protection',
        'description_en' => 'Improving lead conversion with clearer customer journeys and campaigns.',
        'description_fr' => 'Amélioration de la conversion grâce à des parcours clients et campagnes clarifiés.',
    ],
];
?>